title: Bunker DVI Dataset
description: Depth-Visual-Inertial Dataset for Robust Indoor 3D Reconstruction
theme: just-the-docs

url: https://charleshamesse.github.io/dvi-dataset/

color_scheme: wider

